### ISSUE TITLE
MFL: auction

### ISSUE THREAD

**Issue by tanho63** [dynastyprocess/ffscrapr#14]
Might end up being a vignette.

**Comment by TheMathNinja** [comment]
Just curious...would this project result in a ff_auction function which returns the results from this page?: https://www51.myfantasyleague.com/[year]/options?L=[league_id]&O=102

I'm very interested to have this!

**Comment by tanho63** [comment]
I think this may live in a vignette (ie example code) rather than a dedicated function. ff_transactions returns auction bids already so it’s just a bit of math on dates

**Comment by tanho63** [comment]
Closing - if you'd like to tackle this as part of #280, please absolutely feel free!
