### ISSUE TITLE
espn: ff_connect [authentication]?

### ISSUE THREAD

**Issue by tanho63** [dynastyprocess/ffscrapr#154]
https://github.com/cwendt94/espn-api/blob/master/espn_api/requests/espn_requests.py

**Comment by tanho63** [comment]
Doesn't look like Python implementation has username/password working right now and they've been working on it a while. Might take a stab at it but unlikely to include in ESPN first version

**Comment by tonyelhabr** [comment]
Are we assuming that the league is public? Or should this work for both public and private leagues?

**Comment by tanho63** [comment]
It should work for private leagues if they can get their own ESPN cookie https://github.com/dynastyprocess/ffscrapr/blob/espn-api/R/espn_connect.R#L60-L65 - basically the user needs to access the browser/devtools and get the SWID and espn_s2 cookie values
