### ISSUE TITLE
Getting N/A player_name for historic MFL seasons

### ISSUE THREAD

**Issue by TheMathNinja** [dynastyprocess/ffscrapr#196]
I'm seeing a lot of N/A values for player_name for historic MFL seasons, particularly from ff_playerscores().

Code: 
FAFL14 <- mfl_connect(season = 2014, league_id = 37677, rate_limit_number = 3, rate_limit_seconds = 6)
ff_playerscores(FAFL14,season = 2014, week = 1)

Result:
# A tibble: 1,129 x 8
   season week  player_id player_name pos   team  points
    <dbl> <chr> <chr>     <chr>       <chr> <chr> <chr> 
 1   2014 1     9099      Ryan, Matt  QB    ATL   74.5  
 2   2014 1     9431      Stafford, ~ QB    LAR   59.1  
 3   2014 1     7401      Roethlisbe~ QB    PIT   43.3  
 4   2014 1     10313     Dalton, An~ QB    DAL   38.3  
 5   2014 1     6929      NA          NA    NA    37.6  
 6   2014 1     4925      Brees, Drew QB    NOS   36.0  
 7   2014 1     3291      NA          NA    NA    35.7  
 8   2014 1     8657      NA          NA    NA    33.3  
 9   2014 1     10695     Luck, Andr~ QB    FA    33.1  
10   2014 1     10279     NA          NA    NA    32.4  

I'm noticing that in the historic pages themselves, I can view player names, but in this code I cannot. Is this a bug, or is impossible to fetch historic player names from MFL?

**Comment by tanho63** [comment]
It should be possible, I think.

**Comment by tanho63** [comment]
For immediate resolution, you can join/fix player names by passing in a conn object with the correct year to get the correct player names, eg.

```
players_2014 <- mfl_players(mfl_connect(2014))
```

**Comment by TheMathNinja** [comment]
Thanks man, I'll keep my eyes peeled for the fix (dad life got me working on only like 30 mins of free time per week haha).

**Comment by tanho63** [comment]
Included in CRAN v1.3.0
