### ISSUE TITLE
Rate limit help

### ISSUE THREAD

**Issue by TheMathNinja** [dynastyprocess/ffscrapr#197]
Hey team,

Sorry I wasn't sure whether to categorize this as a bug or feature request, but I had a question about rate limits and how they work. 

I got this error message today:
Error: You've hit the MFL rate limit wall! Please adjust the
built-in rate_limit arguments in mfl_connect()!

But I'm not sure entirely how to adjust the arguments so that the code will run properly. I was using
rate_limit_number = 3, rate_limit_seconds = 6, 
since that was in your example.

When I hit the wall like this, how can I adjust my numbers to get around the wall? Should they go up or down? Do I have to wait a certain amount of time? I just wasn't able to find help in understanding these phrases and the details of MFL's specific wall. Thanks.

**Comment by tanho63** [comment]
https://api.myfantasyleague.com/2020/api_info has some more details - I'd recommend registering a user agent, it'll give you more freedom from the MFL API. 

rate_limit_number is the number of calls to make in rate_limit_seconds - so that's three calls in six seconds. 

I generally have no trouble with three calls in six seconds while providing a user agent - you may need to adjust it to something like two calls in six seconds

**Comment by tanho63** [comment]
Lemme know if you need further help on this one :)

**Comment by TheMathNinja** [comment]
Lately I've just been waiting one or two seconds between manually running chunks of code to do this. It's not a great long-term solution but I'm getting by. Any tips for how to build this kind of a "one-second break" between lines of code in my functions to avoid the rate limit? Basically what's happening is that it can handle calling ff_starters() once, but if I ask it to do this in sequence 7 times for 7 years of a league, it hits the rate limit and freezes up.

**Comment by tanho63** [comment]
Did you set up a user_agent with MFL?

**Comment by TheMathNinja** [comment]
No I didn't understand how to fill out their form (I don't understand what a Client Name, Client Description, and Client User Agent mean, or what is smart to put there). Any tips or cheatsheet for understanding these words and their implications? Anyway, since I didn't do that, I just tried to follow tip #1 of theirs, which is to space our requests by a second or two.

**Comment by tanho63** [comment]
Client Name = your name (or your program/company etc)
Client Description = what you want to do with the data
Client User Agent = "username" that you want to use

**Comment by tanho63** [comment]
spacing out requests can be done by doing 1 `rate_limit_number` per 2 `rate_limit_seconds` - which should enforce what you wanted

**Comment by TheMathNinja** [comment]
Great, thanks. The vectorizing of playerscores() plus creating a client has solved this issue for the time being :)
