### ISSUE TITLE
ff_starters error

### ISSUE THREAD

**Issue by TheMathNinja** [dynastyprocess/ffscrapr#202]
Using current dev version of ffscrapr.
Passed an MFL conn object to ff_starters with no other input. Got this error:

> starts_data <- ff_starters(FAFL20)
Error in ff_starters.mfl_conn(FAFL20) : 
  Assertion on 'week' failed: Must be of type 'numeric', not 'character'.

Based on the function readme, I assumed that maybe it would use all weeks as the default if not specified, but it doesn't seem to be able to handle not having weeks specified. I think this is a bug but not sure.

**Comment by TheMathNinja** [comment]
Also, I have a second bug to report. Once I specify week = 1:16, the function works, but...the player_name, pos, and team variables are all NA except in a very few instances (the other columns are correct to my eyes).

Also, I'm sure this matters less, but I also noticed that the starters are listed in the same order as they appear on the "Weekly Results" page in MFL (i.e. sorted by position), but that the nonstarters are not sorted in the same way. Seems like it would be nice.

**Comment by tanho63** [comment]
Good catches, two separate bugs on the same page!

**Comment by TheMathNinja** [comment]
This definitely fixed the major issue but I'm still noticing that non-starters are not sorted by position the way starters are.

**Comment by tanho63** [comment]
Probably would require converting to factor but that creates more problems for end users in my opinion, so I'll shelve that one for now

**Comment by tanho63** [comment]
Initial starters bug has been included in CRAN v1.3.0 - nonstarter/starter sort probably is a wont-fix at this time but please feel free to bring it up again later
