### ISSUE TITLE
Allow range for "week" input in ff_playerscores()

### ISSUE THREAD

**Issue by TheMathNinja** [dynastyprocess/ffscrapr#206]
I'd like to request the ability to enter week = 1:16 into ff_playerscores(). It would significantly simplify my code to be able to fetch any range of scores. Totally understand if this isn't possible but I noticed this is an ability in other functions like ff_starters() and thought it might be possible here too. Thanks!

**Comment by TheMathNinja** [comment]
Looks great, but also I have a new issue now. I'm joining ff_playerscores() to ff_starters() and wanted to point out that "week" is of char type in ff_playerscores() but int type in ff_starters(). Obviously I can work around that but it seems like it might be a plus to just have ff_playerscores() make "week" an int natively.

**Comment by tanho63** [comment]
That’s partially because playerscores also has “YTD” and “AVG” options. Can’t be fixed

-
Tan Ho
________________________________

**Comment by TheMathNinja** [comment]
oh, ok. Also...somewhat related. Have you considered making franchise_id an int instead of char type? At least for deluxe leagues like mine it's often important to treat it as such to easily create conference categories. There might be advantages to keeping it as char, but wanted to throw it out there.

**Comment by tanho63** [comment]
I haven't thought about it, but in my experience, ID columns should always
be character - the idea of math on IDs doesn't really make sense

*Tan Ho*

**Comment by TheMathNinja** [comment]
Makes sense.

**Comment by tanho63** [comment]
Included in CRAN v1.3.0
