### ISSUE TITLE
ff_transaction() bid_amount is of chr type

### ISSUE THREAD

**Issue by TheMathNinja** [dynastyprocess/ffscrapr#210]
I'm currently wanting to rank players in my league by their auction price. I'm running into issues with my ranking code because there are discrepancies in the variable type for the bid_amount variable retrieved by ff_transactions(). 

Here's my code:
FAFL20 <- mfl_connect(season = 2020, league_id = 22686, rate_limit_number = 3, rate_limit_seconds = 6)
auc_results_20 <- ff_transactions(FAFL20) %>%
  filter(type == "AUCTION_WON") %>%
  mutate(bid_rank = rank(desc(bid_amount))) %>%
  ungroup() %>%
  arrange(bid_rank)

Two clear issues:
1. Identical values are being ranked differently (Ertz and Chark are tied because they are both 9.60 but Hollywood and Cooks are ranked below them because they are 9.6. But these should all be tied). 
2. The highest paid players are ranked way down in the last because char type is treating them that way. For example, Garoppolo is rank 260.5 at $3. But then Christian McCaffrey is ranked 269 at $27 (ranked later because 2 comes after 3).

It seems like the problem is that bid_amount is chr type of variable.

**Comment by TheMathNinja** [comment]
But big props to you Tan for already teaching me the parse_number() workaround for now haha. I imagine you might just build that into the function?

**Comment by tanho63** [comment]
I can check, I think there's a good place to include it actually

**Comment by tanho63** [comment]
Included in CRAN v1.3.0
