### ISSUE TITLE
Handling MFL position changes

### ISSUE THREAD

**Issue by TheMathNinja** [dynastyprocess/ffscrapr#211]
My league:
FAFL20 <- mfl_connect(season = 2020, league_id = 22686)
uses "True Position" IDP designations so that "DE" refers generally to Edge and "DT" to Defensive Interior.

For example (let's use Steelers):
T.J. Watt and Bud Dupree are re-assigned to DE from LB
Cameron Heyward and Stephon Tuitt are re-assigned to DT from DE

For all the functions I can tell (incl. ff_rosters(), ff_transactions(), ff_playerscores()), it seems like the "pos" variable uses MFL's default variable, rather than their actual position in my league. Is there a way to read in position changes from MFL so that these functions can return the correct position designations for these players? Thanks. (Honestly, it would be helpful to still maintain the defaults as another variable...maybe "pos" and "custom_pos"?)

Thanks.

**Comment by tanho63** [comment]
For performance reasons the default is to run mfl_players() alone (and is cached) - I believe mfl_players(FAFL20) will return the correct designations which you can manually join onto your reports etc

**Comment by TheMathNinja** [comment]
Works like a charm! Thanks man!
