### ISSUE TITLE
Function for fetching starting requirements?

### ISSUE THREAD

**Issue by TheMathNinja** [dynastyprocess/ffscrapr#214]
Wondering if there's a way to include a function to get starting requirements in this package?

Something that can tell me the minimum and maximum players allowed at a given position, and the total numbers of starters required by the league. Thanks.

**Comment by tanho63** [comment]
Hmm, if this isn't already a feature it may be a while coming. Might be a good time for you to get your feet wet with using `mfl_getendpoint()`! https://api.myfantasyleague.com/2021/api_info?STATE=test&CCAT=export&TYPE=league

**Comment by tanho63** [comment]
Will be resolved in 1.4.0 with `ff_starter_positions()`, now in dev and awaiting CRAN
