### ISSUE TITLE
Issue with getting starters from sleeper

### ISSUE THREAD

**Issue by catz15** [dynastyprocess/ffscrapr#229]
**Describe the bug**
getting Error: Join columns must be present in data.
x Problem with `franchise_id`.when trying to get sleeper starters from 2020

I have been trying this code along with a couple variations. I always get the same error.  

Frannies2020 =sleeper_connect(season = 2020, league_id = 	"649912661714235392")
starter = ff_starters(Frannies2020,week=1:17, season = 2020)

**Comment by tanho63** [comment]
Hi there! It looks like this is a 2021 league ID, not a 2020 one. You can use `ff_league()` to find previous league IDs: 
![image](https://user-images.githubusercontent.com/38083823/109718153-f7474d00-7b74-11eb-968a-7f099ce967dd.png)

**Comment by catz15** [comment]
Awesome. Thanks
