### ISSUE TITLE
str_ functions work much faster with stringr::fixed() wrapping search terms

### ISSUE THREAD

**Issue by tanho63** [dynastyprocess/ffscrapr#238]
c/o @mrcaseb

**Comment by mrcaseb** [comment]
You should make sure it works fine on different Operating Systems with different language settings. I am not 100% sure if this can get you in trouble, esp. for non-ASCII sets

see: https://stringr.tidyverse.org/reference/modifiers.html

**Comment by tanho63** [comment]
Yea, but API responses `should` come back the same encoding every time 🤞

**Comment by tanho63** [comment]
Speed gain turned out to be minimal, not doing a lot of regex parsing apparently! 

Closing without making changes at this time - no need to add more complexity for no gain
