### ISSUE TITLE
mfl_playerscores has inconsistent positions

### ISSUE THREAD

**Issue by TheMathNinja** [dynastyprocess/ffscrapr#239]
I think this is something new on account of the release of 1.3, but I'm noticing that some of my old code is broken because it looks like ff_starters() is using a different method for fetching player position than previously.

Previously, both ff_playerscores() and ff_starters() displayed MFL default position for the "pos" variable. But now, ff_starters() displays the custom position, while ff_playerscores() still displays MFL default.

It makes sense to me that in ff_starters() you want to display the position the player actually started at rather than his default position, but for people like me who are joining df's together by a shared variable like "pos", this presents an issue.

I'm not sure I know the best fix for something like this, but is it possible to have separate columns in both for default and custom position? Or, if you think keeping it inconsistent is the best way forward, I can just change my code to account for it.

**Comment by tanho63** [comment]
df's like that should be joined by ID, no?

**Comment by tanho63** [comment]
Looks like it's this line that's the trouble, it should also pass leagueID from the conn https://github.com/dynastyprocess/ffscrapr/blob/ab1fe788e70ad443bbaf5eab67fcdfe22ce89361/R/mfl_playerscores.R#L37

Probably will make it to next patch

**Comment by TheMathNinja** [comment]
I was joining by ID and by pos to catch instances like this. So you will be amending ff_playerscores() then? Not ff_starters()? If you amend playerscores, then pos will always be the custom position and not MFL default? If you go this way, is there any way I can retrieve MFL default position for these players still? 

What I had been doing previously was keeping MFL default via these functions and then joining custom positions at the end via the mfl_players() function.

**Comment by tanho63** [comment]
mfl_playerscores will return the position that the league uses. If you want default positions you'll need to join on `mfl_players()` without the league ID

**Comment by TheMathNinja** [comment]
Great, thanks for the quick reply, @tanho63!

**Comment by TheMathNinja** [comment]
And just for clarification...I will want the season-specific default for mfl_players, but not the league, right?

**Comment by tanho63** [comment]
Yes, although a separate issue could probably be raised to have a season argument in mfl players

**Comment by TheMathNinja** [comment]
Haha I'll leave that up to your discernment.

**Comment by TheMathNinja** [comment]
I'm still having this issue running 1.3.0001. Is this not the fix that was included in that version? Sorry if I'm misunderstanding what the pull request did.

**Comment by tanho63** [comment]
Pull request hasn’t made it into dev yet, it’s still “open” - I was insomniac the other night and tried doing it all from my phone...but it needs some help with tests

**Comment by tanho63** [comment]
This should now be reflected in 1.3.0002
