### ISSUE TITLE
ff_transactions() warning

### ISSUE THREAD

**Issue by TheMathNinja** [dynastyprocess/ffscrapr#243]
When I run ff_transactions() on this league:
 mfl_connect(season = 2017, league_id = 22686)

I get this warning message: 
Warning message:
Problem with `mutate()` input `bid_amount`.
i NAs introduced by coercion
i Input `bid_amount` is `as.numeric(.data$bid_amount)`.

I know we used the MFL feature of bids being presented in millions in that season. It seems like something in ff_transactions() is struggling with that format of bids. It has the same issue with 2016 for that league ID.

**Comment by tanho63** [comment]
![image](https://user-images.githubusercontent.com/38083823/113007992-aa8b6d80-9144-11eb-9cd6-b5a084582a95.png)

Kind of odd. Looks like there's just this one bug where someone accidentally put in a `\` character into their bid - everything else looks normal

**Comment by tanho63** [comment]
In normal coding I'd just switch to  readr's parse_number here, but I'm not sure I want to introduce another dependency. Lemme think about what to do with it here

**Comment by TheMathNinja** [comment]
Did you check 2016 also? I got this warning for 4 different years in a row.

**Comment by tanho63** [comment]
Same problems - random garbage in the numeric field. Thinking about how to solve, probably will write my own string parser rather than add another dependency


![image](https://user-images.githubusercontent.com/38083823/113037286-3ad8ab00-9163-11eb-9583-ce878902f1c5.png)

**Comment by tanho63** [comment]
Should be included in dev as of 1.3.0.12

**Comment by TheMathNinja** [comment]
I'm using 1.3.0.12 but still getting an error for 
```
ff_transactions(mfl_connect(season = 2015, league_id = 27312))
Warning message:
Problem with `mutate()` input `bid_amount`.
i NAs introduced by coercion
i Input `bid_amount` is ``%>%`(...)`.
```

**Comment by tanho63** [comment]
hmm, trailing dashes. the whole problem seems to be that mfl stores whatever is put into the bid amount field even if it's not a number. should be ok now

**Comment by TheMathNinja** [comment]
Yay it works!
