### ISSUE TITLE
Week is chr type in ff_playerscores()

### ISSUE THREAD

**Issue by TheMathNinja** [dynastyprocess/ffscrapr#258]
Sorry if you've explained this elsewhere, but I'm noticing that season is dbl and week is chr in ff_playerscores() for MFL objects. Shouldn't week be dbl?

**Comment by TheMathNinja** [comment]
I noticed this also for draft_year and draft_round in ff_rosters()

**Comment by tanho63** [comment]
Mostly because it’s returned as character by the API
