### ISSUE TITLE
Current age in ff_draft()

### ISSUE THREAD

**Issue by TheMathNinja** [dynastyprocess/ffscrapr#259]
I'm using the ff_draft() function on an MFL object and realizing that the age variable is showing the player's current age rather than age at the time of draft. Is this how it is meant to perform? It seems like age at the time the pick was made might be more useful.

**Comment by tanho63** [comment]
Probably lazy joining mfl players rather than redoing math. Can be fixed, not sure if will make next CRAN update. (Possibly).
