### ISSUE TITLE
Overall Pick variable in ff_draft()

### ISSUE THREAD

**Issue by TheMathNinja** [dynastyprocess/ffscrapr#260]
Is it possible to read in the overall pick number as its own variable in the ff_draft() function? (I know MFL's draft report calls this "ovr"). Currently ff_draft() just returns round number and pick within the round.

Especially in leagues that use compensatory picks or toilet bowl sorts of bonus picks at ends of rounds, getting this number directly from the source rather than creating it via scripts could be really helpful, thanks.

**Comment by tanho63** [comment]
This is just dplyr::row_number I think

**Comment by TheMathNinja** [comment]
If you run Deluxe Leagues in MFL and it returns multiple drafts, then that doesn't quite work super simply (needs a group_by). Anyway, I just thought MFL probably supplied it since it's in the draft readout. But if it bogs down the package, no worries.

**Comment by tanho63** [comment]
aye, probably, got an example league/

*Tan Ho*

**Comment by TheMathNinja** [comment]
I do have an example, but I don't have a problem in my code. It works just fine. But if you want one to play around with, the league is league_id 60206 on MFL. Any year 2016-2020 will work.
