### ISSUE TITLE
ff_scoringhistory() missing variables

### ISSUE THREAD

**Issue by TheMathNinja** [dynastyprocess/ffscrapr#265]
I'm running:

```
FAFL20 <- mfl_connect(season = 2020, league_id = 22686)
structure(ff_scoringhistory(FAFL20, season = 2020))
```

And seeing that:
```
sack_fumbles_lost
passing_first_downs
rushing_fumbles_lost
rushing_first_downs
receiving_fumbles_lost
receiving_first_downs
special_teams_tds
```

are all excluded from the df.

**Comment by tanho63** [comment]
Probably needs a revisit of join order 
![image](https://user-images.githubusercontent.com/38083823/114572515-8dc35f80-9c45-11eb-8a53-77367fc7f933.png)

**Comment by TheMathNinja** [comment]
Also, Fumbles and Sack Yards are missing. These are going to be HUGE ;-)

**Comment by tanho63** [comment]
added
```
first_downs
receiving_fumbles_lost
rushing_fumbles_lost
sack_fumbles
rushing_fumbles
receiving_fumbles
```

It looks like your example league doesn't have kick/punt return TDs? @TheMathNinja

**Comment by TheMathNinja** [comment]
No return TDs. But wait what about sack yards??

**Comment by tanho63** [comment]
It should be there!

**Comment by TheMathNinja** [comment]
Lol. Admittedly I haven’t run the function I just didn’t see it in your above list
