### ISSUE TITLE
Add week parameter to ff_rosters() for ESPN

### ISSUE THREAD

**Issue by scottfrechette** [dynastyprocess/ffscrapr#276]
Currently ff_rosters() will return latest week but by adding an additional parameter end user can select specific week:

sucioboys <- ffscrapr::espn_connect(season = 2020, league_id = 899513)
ffscrapr::espn_getendpoint(sucioboys, view = "mRoster") 
#> <ESPN - GET https://fantasy.espn.com/apis/v3/games/ffl/seasons/2020/segments/0/leagues/899513?view=mRoster>
#> List of 8
#>  $ draftDetail    :List of 2
#>  $ gameId         : int 1
#>  $ id             : int 899513
#>  $ scoringPeriodId: int 18
#>  $ seasonId       : int 2020
#>  $ segmentId      : int 0
#>  $ status         :List of 21
#>  $ teams          :List of 10
ffscrapr::espn_getendpoint(sucioboys, view = "mRoster", scoringPeriodId = 1) 
#> <ESPN - GET https://fantasy.espn.com/apis/v3/games/ffl/seasons/2020/segments/0/leagues/899513?view=mRoster&scoringPeriodId=1>
#> List of 8
#>  $ draftDetail    :List of 2
#>  $ gameId         : int 1
#>  $ id             : int 899513
#>  $ scoringPeriodId: int 1
#>  $ seasonId       : int 2020
#>  $ segmentId      : int 0
#>  $ status         :List of 21
#>  $ teams          :List of 10

**Comment by tanho63** [comment]
Hm! Definitely doable, I think.

**Comment by TheMathNinja** [comment]
I know MFL also has separate roster pages for each week (but beware that while personnel is correct for every week, the player’s status is not necessarily true of that week)

**Comment by tanho63** [comment]
@scottfrechette this is added to the dev branch (v1.4.1.01+) - if you'd like to take it for a test spin, please run

```
remotes::install_github("dynastyprocess/ffscrapr", ref = "dev")
```

**Comment by scottfrechette** [comment]
I’m getting an error:

remotes::install_github("dynastyprocess/ffscrapr", ref = "dev")

#> Skipping install of 'ffscrapr' from a github remote, the SHA1 (e06de53f) has not changed since last install.

#>   Use `force = TRUE` to force installation

sucioboys <- ffscrapr::espn_connect(season = 2020, league_id = 899513)

ffscrapr::ff_rosters(sucioboys)

#> Error in ff_franchises.espn_conn(conn): attempt to apply non-function

ffscrapr::ff_rosters(sucioboys, week = 1)

#> Error in `_cache`$digest(c(body(`_f`), args, lapply(`_additional`, function(x) eval(x[[2L]], : attempt to apply non-function

**Comment by tanho63** [comment]
Hmm. Try restarting R, running

```
remotes::install_github("dynastyprocess/ffscrapr", ref = "dev", force = TRUE)
ffscrapr::.ff_clear_cache()
```
and seeing if that helps?

**Comment by scottfrechette** [comment]
Tried my non-work computer and error is gone. Should have known better.

It seems acquisition type/date isn't available when week is selected. Not sure how much it matters but I'm trying to add another view would bring that back in.

**Comment by tanho63** [comment]
That's a bummer! Let me know if you figure something out :)

**Comment by scottfrechette** [comment]
I've tried to add in every other endpoint and just can't make those two fields populate in anything except latest week (currently 18). 

Not sure how much those matter, probably fine to just leave them NULL but what a weird quirk.

**Comment by tanho63** [comment]
Sucky to hear! Could probably use `tidyr::fill` in personal usage to fill in previous weeks
