### ISSUE TITLE
Feature: name-mapping for `dp_cleannames()`

### ISSUE THREAD

**Issue by tanho63** [dynastyprocess/ffscrapr#284]
Create a mapping of common name-join issues such as pat vs patrick mahomes, mitch vs mitchell trubisky, rob vs robert kelley etc.

If you're reading this and have more, please feel free to add a comment below!

**Comment by joeflan** [comment]
Are we thinking a hard coded mapping for names or a programmatic way?

**Comment by tanho63** [comment]
Hmm. I was thinking of hardcoded mappings for the weird ones specifically. Sleeper’s API works well and helps power dp_playerids() already

**Comment by tanho63** [comment]
- [ ] Foye to Foyesade Oluokun
