### ISSUE TITLE
ff_league should return the season as a column of the dataframe

### ISSUE THREAD

**Issue by tanho63** [dynastyprocess/ffscrapr#287]

**Comment by joeflan** [comment]
I forked this and I'm going to start taking a look

**Comment by tanho63** [comment]
Nice! It’s a pretty simple fix, just add season = conn$season to the returned tibble

**Comment by joeflan** [comment]
Is the issue officially closed when the changes are merged into main?

**Comment by tanho63** [comment]
Yeah, hopefully automatically but sometimes I go back and clean them. This is definitely fully completed though
