### ISSUE TITLE
ff_schedule include sleeper playoffs

### ISSUE THREAD

**Issue by draftydesert277** [dynastyprocess/ffscrapr#289]
I noticed that ff_schedule() pulls playoff data for MFL but not Sleeper. I'm able to see the playoff schedule data by calling the sleeper matchups API directly (e.g. "week = 14" in my 13-game league).

The only way around this that I've found is rebuilding the schedule data by hand using httr & jsonlite, but I assume that's kind of the point of ff_schedule() to begin with. I'm sure this was done for a good reason but curious what the options are here. Thanks!

**Comment by tanho63** [comment]
Hiya! Great question. I don't recall why I wrote this logic in, to be honest...

https://github.com/dynastyprocess/ffscrapr/blob/main/R/sleeper_schedule.R#L19-L27

**Comment by tanho63** [comment]
Hmm, I probably wrote that because there wasn't a playoff matchup to pull pre-season and it caused breakage if you tried pulling it.

Could figure out the maximum of regular_season_end + last_scored_week and take the higher of the two...

**Comment by draftydesert277** [comment]
Makes sense, hadn't considered that! That seems like it would work. I assume MFL doesn't create similar headaches when pulling schedule info mid-season.

I'm working on some league history type analysis (e.g. best playoff performers), so I'm pulling all weeks and then flagging 14-16 as playoffs after the fact.

**Comment by tanho63** [comment]
Okay, this should be resolved by dev version 1.4.2.03 and later

**Comment by draftydesert277** [comment]
Just downloaded the dev version and this is working - thanks!

**Comment by tanho63** [comment]
Included in v1.4.3 released today
