### ISSUE TITLE
Adding "week" argument to ff_standings

### ISSUE THREAD

**Issue by TheMathNinja** [DynastyProcess/ffscrapr#67]
I'm brand new to the package, and still fairly new to R, so please forgive me if I'm just doing this wrong. I was looking at ff_standings, and wondering if there's a way to get standings which are specific to any point in the season. I'd like to be able to separate standings at the end of the regular season from standings at the end of the playoffs, for example. Thanks!

**Comment by tanho63** [comment]
Hm, great question! 

I don’t believe it’s a feature of the original API endpoint

https://api.myfantasyleague.com/2020/api_info?STATE=test&CCAT=export&TYPE=leagueStandings

but you could maybe recreate the effect you’re looking for by summarizing the ff_schedule output?

**Comment by tanho63** [comment]
Actually, I think the other thing to wonder is if MFL tacks on playoff victories into their “standings”. I seem to recall it always being regular season only

**Comment by TheMathNinja** [comment]
On the Standings Setup page: http://www51.myfantasyleague.com/[year]/csetup?L=[league_id]&C=STANDINGS

There is an option which says: "Stop updating league standings report after week". This determines when the standings report stops updating. This doesn't appear it can be changed for legacy league pages. So if you set this number to include playoffs, it will include those weeks, and if not, it won't. However, I've found that it often includes All-Play standings on a separate schedule. For example, I have one league year (2014) where I had it set only to calculate regular season standings (through week 12) but it calculated all-play through Week 17 (even though we had no week 17 matchups assigned). I have another league year (2019) where I had it set to calculate all standings (through week 16) and it calculated all-play through Week 16 also. I'm doing an analysis where I want to compare apples to apples (i.e. 16-week all-play to 16-week all-play across years). So I'm wondering if we can get this function updated such that it can use week as an input for comparing apples to apples.

**Comment by tanho63** [comment]
Hmm. That's not actually exposed on their API (api.myfantasyleague.com) - I can't force MFL to change the commissioner settings for standings via an R function. 

I might be able to make you an example snippet on calculating 16-week all plays based on the schedule/matchup endpoint via ff_schedule, what leagueID/years are you looking for?

**Comment by TheMathNinja** [comment]
Yeah I figured about forcing MFL. Would love the snipped for calculating 16-week all plays! These are the leagues I'm analyzing:
FAFL14 <- mfl_connect(season = 2014, league_id = 37677)
FAFL15 <- mfl_connect(season = 2015, league_id = 27312)
FAFL16 <- mfl_connect(season = 2016, league_id = 22686)
FAFL17 <- mfl_connect(season = 2017, league_id = 22686)
FAFL18 <- mfl_connect(season = 2018, league_id = 22686)
FAFL19 <- mfl_connect(season = 2019, league_id = 22686)

Would you also be able to include snippets for calculating 16-week points for? I'm noticing that the function is returning only the weeks which standings are counted for in "points_for" (often 12), but returning the 17-week all-play result in the all_play_wins function. So these are inconsistent data points. 

Also, I realize this is a somewhat separate issue perhaps (but a bit related). I'm noticing the ff_standings function includes total points and potential points. I'm wondering if it can be adjusted to also include offensive points and defensive points? Once again, I would be very interested in all 4 of these points functions being able to return week-specified amounts.

**Comment by tanho63** [comment]
> Also, I realize this is a somewhat separate issue perhaps (but a bit related). I'm noticing the ff_standings function includes total points and potential points. I'm wondering if it can be adjusted to also include offensive points and defensive points? Once again, I would be very interested in all 4 of these points functions being able to return week-specified amounts.

OH SO THAT'S WHAT OP AND DP ARE! OP and DP do exist at a season-summary level and can be added in next ver. Less sure about week level - that would be a snippet/function, most likely.

**Comment by tanho63** [comment]
This may be a starting point: 
```
library(ffscrapr)
library(tidyverse)

FAFL14 <- mfl_connect(season = 2014, league_id = 37677)
FAFL15 <- mfl_connect(season = 2015, league_id = 27312)
FAFL16 <- mfl_connect(season = 2016, league_id = 22686)
FAFL17 <- mfl_connect(season = 2017, league_id = 22686)
FAFL18 <- mfl_connect(season = 2018, league_id = 22686)
FAFL19 <- mfl_connect(season = 2019, league_id = 22686)

custom_summary <- function(conn, week_select = c(1:16)){
  
  df_schedule <- ff_schedule(conn)
  
  df_schedule %>%
    filter(week %in% week_select) %>% 
    filter(franchise_id != "BYE") %>%
    arrange(week,franchise_score) %>% 
    group_by(week) %>% 
    mutate(all_play_wins = rank(franchise_score)-1,
           all_play_games = n()-1) %>% 
    ungroup() %>% 
    group_by(franchise_id) %>% 
    summarise(
      points_for = sum(franchise_score,na.rm = TRUE),
      all_play_wins = sum(all_play_wins),
      all_play_games = sum(all_play_games),
      all_play_pct = round(all_play_wins/all_play_games,3)
    )
}

df <- tibble(
  year = 2014:2019,
  conn = list(FAFL14,FAFL15,FAFL16,FAFL17,FAFL18,FAFL19)
) %>% 
  mutate(custom_summary = map(conn,custom_summary,1:16))
```

**Comment by TheMathNinja** [comment]
Thanks for this! I'll give it a run soon. Do you think it would make sense for this eventually to turn into a "week" argument in the ff_standings function or no? I guess the week function could only easily read/automate all play and points, but not win-loss?

**Comment by tanho63** [comment]
I don't think so offhand because it's approaching the problem in a different way than I had intended to - the ff_standings function is meant to return exactly what is displayed in MFL as your standings, while this function rebuilds "standings" from "schedule". Win pct is actually not difficult to recreate from here as part of the summarise function:

```
custom_summary <- function(conn, week_select = c(1:16)){
  
  df_schedule <- ff_schedule(conn)
  
  df_schedule %>%
    filter(week %in% week_select) %>% 
    filter(franchise_id!="BYE") %>% 
    arrange(week,franchise_score) %>% 
    group_by(week) %>% 
    mutate(all_play_wins = rank(franchise_score)-1,
           all_play_games = n()-1) %>% 
    ungroup() %>% 
    group_by(franchise_id) %>% 
    summarise(
      points_for = sum(franchise_score,na.rm = TRUE),
      wins = sum(result == "W"),
      games = n(),
      win_pct = wins/games,
      all_play_wins = sum(all_play_wins),
      all_play_games = sum(all_play_games),
      all_play_pct = round(all_play_wins/all_play_games,3)
    )
}
```

**Comment by tanho63** [comment]
Marking as tentatively resolved
