### ISSUE TITLE
ff_starters feature

### ISSUE THREAD

**Issue by TheMathNinja** [dynastyprocess/ffscrapr#76]
Hey guys, I'm wondering if you've considered a ff_starters() function or feature, or whether you've looked at that part of MFL's API. Please let me know if the package currently supports/reveals the data from this page: http://www51.myfantasyleague.com/[year]/options?L=[league_id]&O=37 or if that could be included in some kind of ff_starters() function. Thanks.

Mike

**Comment by tanho63** [comment]
Hmm, I know it's not an evident endpoint out of the API. Possibly related
to weeklyResults + playerScores + ?.

Joe's code in https://github.com/dynastyprocess/research does this via the
mfl_getendpoint function, I think. I'll have a think about how this fits
the overall scope of the package, and whether the same thing can be
replicated on other platforms.

Tan

*Tan Ho*
